local M = {}

function M.apply(name, background, p, terminal)
  vim.g.colors_name = nil
  vim.o.background = background
  vim.cmd.colorscheme("quiet")
  vim.g.colors_name = name

  local highlights = {
    Normal = { fg = p.fg, bg = p.bg },
    NormalNC = { link = "Normal" },
    NormalFloat = { fg = p.fg, bg = p.panel },
    FloatBorder = { fg = p.muted, bg = p.panel },
    FloatTitle = { fg = p.fg, bg = p.panel, bold = true },
    ColorColumn = { bg = p.line },
    CursorLine = { bg = p.line },
    CursorColumn = { bg = p.line },
    Cursor = { fg = p.cursor_text, bg = p.cursor },
    CursorInsert = { fg = p.bg, bg = p.insert_cursor },
    CursorIM = { link = "Cursor" },
    lCursor = { link = "Cursor" },
    TermCursor = { link = "Cursor" },
    LineNr = { fg = p.muted },
    CursorLineNr = { fg = p.fg, bg = p.line, bold = true },
    SignColumn = { fg = p.muted, bg = p.bg },
    EndOfBuffer = { fg = p.bg },
    NonText = { fg = p.border },
    Whitespace = { fg = p.border },
    SpecialKey = { fg = p.muted },
    Conceal = { fg = p.muted },
    FoldColumn = { fg = p.muted, bg = p.bg },
    Folded = { fg = p.muted, bg = p.panel },
    WinSeparator = { fg = p.border, bg = p.bg },
    VertSplit = { link = "WinSeparator" },
    Visual = { fg = p.fg, bg = p.selection },
    VisualNOS = { link = "Visual" },
    Search = { fg = p.fg, bg = p.search },
    IncSearch = { fg = p.bg, bg = p.yellow },
    CurSearch = { link = "IncSearch" },
    MatchParen = { fg = p.fg, bg = p.selection, bold = true },
    QuickFixLine = { fg = p.fg, bg = p.selection },
    StatusLine = { fg = p.fg, bg = p.panel },
    StatusLineNC = { fg = p.muted, bg = p.panel },
    TabLine = { fg = p.muted, bg = p.panel },
    TabLineFill = { bg = p.panel },
    TabLineSel = { fg = p.fg, bg = p.bg, bold = true },
    WinBar = { fg = p.fg, bg = p.bg, bold = true },
    WinBarNC = { fg = p.muted, bg = p.bg },
    Pmenu = { fg = p.fg, bg = p.panel },
    PmenuSel = { fg = p.fg, bg = p.selection },
    PmenuExtra = { fg = p.muted, bg = p.panel },
    PmenuExtraSel = { link = "PmenuSel" },
    PmenuKind = { fg = p.blue, bg = p.panel },
    PmenuKindSel = { link = "PmenuSel" },
    PmenuMatch = { fg = p.blue, bg = p.panel, bold = true },
    PmenuMatchSel = { fg = p.fg, bg = p.selection, bold = true },
    PmenuSbar = { bg = p.panel },
    PmenuThumb = { bg = p.border },
    WildMenu = { link = "PmenuSel" },
    Comment = { fg = p.muted, italic = true },
    Constant = { fg = p.yellow },
    Boolean = { fg = p.purple },
    Character = { link = "String" },
    String = { fg = p.green },
    Identifier = { fg = p.fg },
    Function = { fg = p.blue },
    Statement = { fg = p.purple },
    Operator = { fg = p.cyan },
    Delimiter = { fg = p.muted },
    PreProc = { fg = p.purple },
    Type = { fg = p.cyan },
    Special = { fg = p.yellow },
    Directory = { fg = p.blue },
    Title = { fg = p.fg, bold = true },
    Underlined = { fg = p.blue, underline = true },
    Todo = { fg = p.yellow, bg = p.panel, bold = true },
    Error = { fg = p.red, underline = true },
    ErrorMsg = { fg = p.red },
    WarningMsg = { fg = p.yellow },
    MoreMsg = { fg = p.green },
    Question = { fg = p.blue },
    ModeMsg = { fg = p.fg, bold = true },
    DiffAdd = { bg = p.diff_add },
    DiffChange = { bg = p.diff_change },
    DiffDelete = { fg = p.red, bg = p.diff_delete },
    DiffText = { bg = p.diff_text, bold = true },
    Added = { fg = p.green },
    Changed = { fg = p.blue },
    Removed = { fg = p.red },
    DiagnosticError = { fg = p.red },
    DiagnosticWarn = { fg = p.yellow },
    DiagnosticInfo = { fg = p.blue },
    DiagnosticHint = { fg = p.cyan },
    DiagnosticOk = { fg = p.green },
    SpellBad = { sp = p.red, undercurl = true },
    SpellCap = { sp = p.blue, undercurl = true },
    SpellRare = { sp = p.purple, undercurl = true },
    SpellLocal = { sp = p.cyan, undercurl = true },
    ["@variable"] = { link = "Identifier" },
    ["@variable.builtin"] = { fg = p.purple },
    ["@variable.parameter"] = { fg = p.yellow },
    ["@variable.member"] = { fg = p.cyan },
    ["@property"] = { link = "@variable.member" },
    ["@constant.builtin"] = { link = "Boolean" },
    ["@function.builtin"] = { link = "Function" },
    ["@constructor"] = { link = "Type" },
    ["@type.builtin"] = { link = "Type" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { link = "Delimiter" },
    ["@lsp.type.variable"] = { link = "@variable" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@variable.member" },
    ["@lsp.type.decorator"] = { link = "@attribute" },
    ["@markup.heading"] = { fg = p.cyan, bold = true },
    ["@markup.strong"] = { fg = p.yellow, bold = true },
    ["@markup.italic"] = { fg = p.purple, italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.link"] = { fg = p.cyan },
    ["@markup.link.label"] = { fg = p.cyan },
    ["@markup.link.url"] = { fg = p.cyan, underline = true },
    ["@markup.raw"] = { fg = p.yellow },
    ["@markup.raw.block"] = { fg = p.fg },
    ["@markup.list"] = { fg = p.green },
    ["@markup.list.checked"] = { fg = p.green },
    ["@markup.list.unchecked"] = { fg = p.yellow },
    ["@markup.quote"] = { fg = p.cyan, italic = true },
    RenderMarkdownCode = { bg = p.panel },
    RenderMarkdownCodeInline = { fg = p.yellow, bg = p.panel },
    RenderMarkdownBullet = { link = "@markup.list" },
    RenderMarkdownQuote = { link = "@markup.quote" },
    RenderMarkdownLink = { link = "@markup.link.label" },
    RenderMarkdownLinkTitle = { link = "@markup.link" },
    RenderMarkdownChecked = { link = "@markup.list.checked" },
    RenderMarkdownUnchecked = { link = "@markup.list.unchecked" },
    RenderMarkdownTodo = { fg = p.purple },
    RenderMarkdownDash = { fg = p.border },
    RenderMarkdownTableHead = { link = "@markup.heading" },
    RenderMarkdownTableRow = { fg = p.muted },
  }

  local headings = { p.yellow, p.green, p.blue, p.purple, p.cyan, p.red }
  for level, color in ipairs(headings) do
    highlights["@markup.heading." .. level] = { fg = color, bold = true }
    highlights["RenderMarkdownH" .. level] = { link = "@markup.heading." .. level }
    highlights["RenderMarkdownH" .. level .. "Bg"] = { fg = color, bg = p.panel }
  end
  for group, definition in pairs(highlights) do
    vim.api.nvim_set_hl(0, group, definition)
  end

  vim.g.terminal_ansi_colors = terminal
  for i, color in ipairs(terminal) do
    vim.g["terminal_color_" .. (i - 1)] = color
  end
end

return M
